FROM openhealthdigital/php-apache:7.1

# Install curl and then Wordpress command line tool (wp-cli)
RUN curl -o /usr/local/bin/wp https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
RUN chmod a+x /usr/local/bin/wp
